/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xtkj_jni_algor_HighwayAlgors */

#ifndef _Included_cn_xtkj_jni_algor_HighwayAlgors
#define _Included_cn_xtkj_jni_algor_HighwayAlgors
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xtkj_jni_algor_HighwayAlgors
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_xtkj_jni_algor_HighwayAlgors_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     cn_xtkj_jni_algor_HighwayAlgors
 * Method:    createInstanceCollections
 * Signature: (Lcn/xtkj/jni/algor/HighwayAlgorParam;[Lcn/xtkj/jni/algor/HighwayExample;)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_xtkj_jni_algor_HighwayAlgors_createInstanceCollections
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     cn_xtkj_jni_algor_HighwayAlgors
 * Method:    changeParam
 * Signature: (Lcn/xtkj/jni/algor/HighwayAlgorParam;)I
 */
JNIEXPORT jint JNICALL Java_cn_xtkj_jni_algor_HighwayAlgors_changeParam
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cn_xtkj_jni_algor_HighwayAlgors
 * Method:    putMat
 * Signature: (ILcn/xtkj/jni/algor/data/MatRef;)J
 */
JNIEXPORT jlong JNICALL Java_cn_xtkj_jni_algor_HighwayAlgors_putMat
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     cn_xtkj_jni_algor_HighwayAlgors
 * Method:    takeRes
 * Signature: (IJ)[Lcn/xtkj/jni/algor/helper/EventYoloCoor;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_xtkj_jni_algor_HighwayAlgors_takeRes
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     cn_xtkj_jni_algor_HighwayAlgors
 * Method:    releaseInstanceCollection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_xtkj_jni_algor_HighwayAlgors_releaseInstanceCollection
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
